#!/usr/bin/env python3
"""Copy the shared EcoNet code into both drivers, and check the package is consistent.

Hubitat installs each driver as one self-contained file (HPM and Import URL both
fetch a single .groovy), so code the two drivers share lives in
shared/EcoNetCommon.groovy and is copied into each driver between the SHARED CODE
markers at the bottom. That keeps one source of truth without asking users to
install a Hubitat library alongside the drivers.

    python3 tools/build.py           rewrite the shared section of both drivers
    python3 tools/build.py --check   change nothing; exit 1 if anything is out of date

--check also verifies:
  - each driver's header "Version:" matches its DRIVER_VERSION field, and both
    drivers carry the same version;
  - packageManifest.json releaseNotes contain no double quote, backtick or dollar
    sign (the release workflow passes them through a double-quoted shell echo);
  - for a final version (no "-beta" style suffix), packageManifest.json matches it.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHARED = ROOT / "shared" / "EcoNetCommon.groovy"
DRIVERS = [ROOT / "EcoNetThermostat.groovy", ROOT / "EcoNetWaterHeater.groovy"]
MANIFEST = ROOT / "packageManifest.json"

BEGIN = "// ===== BEGIN SHARED CODE (shared/EcoNetCommon.groovy) ====="
NOTE = "// Generated by tools/build.py. Do not edit here: edit the shared file and rebuild."
END = "// ===== END SHARED CODE ====="


def render(driver_text: str, shared_text: str, name: str) -> str:
    start = driver_text.find(BEGIN)
    stop = driver_text.find(END)
    if start < 0 or stop < 0 or stop < start:
        raise SystemExit(f"{name}: SHARED CODE markers missing or out of order")
    block = f"{BEGIN}\n{NOTE}\n\n{shared_text.rstrip()}\n\n{END}"
    return driver_text[:start] + block + driver_text[stop + len(END):]


def versions(text: str, name: str):
    header = re.search(r"^\s*\*\s*Version:\s*(\S+)", text, re.M)
    field = re.search(r'@Field\s+(?:static\s+final\s+)?String\s+DRIVER_VERSION\s*=\s*"([^"]+)"', text)
    if not header or not field:
        raise SystemExit(f"{name}: header 'Version:' line or DRIVER_VERSION field not found")
    return header.group(1), field.group(1)


def main(argv):
    check = "--check" in argv
    shared = SHARED.read_text(encoding="utf-8")
    problems = []
    found_versions = set()

    for path in DRIVERS:
        text = path.read_text(encoding="utf-8")
        new = render(text, shared, path.name)
        if new != text:
            if check:
                problems.append(f"{path.name}: shared section is out of date or was edited by hand — run tools/build.py")
            else:
                path.write_text(new, encoding="utf-8")
                print(f"updated {path.name}")
        header, field = versions(new, path.name)
        if header != field:
            problems.append(f"{path.name}: header says {header} but DRIVER_VERSION is {field}")
        found_versions.add(field)

    if len(found_versions) > 1:
        problems.append(f"drivers disagree on version: {sorted(found_versions)}")

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    notes = manifest.get("releaseNotes", "")
    bad = sorted({c for c in notes if c in '"`$'})
    if bad:
        problems.append(f"packageManifest.json releaseNotes contain {' '.join(bad)} — the release workflow's echo breaks on these")
    version = next(iter(found_versions)) if len(found_versions) == 1 else None
    if version and "-" not in version and manifest.get("version") != version:
        problems.append(f"drivers are {version} but packageManifest.json says {manifest.get('version')}")

    for p in problems:
        print(f"ERROR: {p}", file=sys.stderr)
    if not problems and check:
        print("shared code, versions and manifest are consistent")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
